/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

// --- STYLE PRESETS ---

export const STYLES = {
  executive: {
    id: 'executive',
    styleDescription: 'a pristine white thobe with a sharp, executive cut and clean lines, featuring a slightly high collar. May include subtle accessories like a pen clipped to the pocket or elegant cufflinks.',
    backgroundDescription: 'a solid, light grey or off-white studio background with professional, soft lighting.',
  },
  bisht: {
    id: 'bisht',
    styleDescription: 'a luxurious black bisht with fine golden embroidery (zari) on the trim, worn over a crisp white thobe and a white ghutra.',
    backgroundDescription: 'a solid, deep charcoal grey background, subtly textured, with dramatic studio lighting to complement the formal attire.',
  },
  shemagh: {
    id: 'shemagh',
    styleDescription: "a light grey thobe made from premium fabric, paired with a red-and-white shemagh folded in a modern 'cobra' style.",
    backgroundDescription: 'a clean, solid medium-grey background with even, modern lighting to highlight the details of the attire.',
  },
  ghutra: {
    id: 'ghutra',
    styleDescription: "a classic white thobe, with a pure white ghutra folded in a formal, balanced Saudi style (butterfly fold).",
    backgroundDescription: 'a solid, off-white or very light beige solid background with natural, soft lighting.',
  },
  luxury: {
    id: 'luxury',
    styleDescription: 'a beige or cream-colored thobe from a luxurious fabric, with a high-end watch clearly visible.',
    backgroundDescription: 'a solid, warm-toned dark taupe background with a subtle gradient and focused lighting.',
  },
  visionary: {
    id: 'visionary',
    styleDescription: 'a dark navy blue thobe with a modern cut, paired with a neatly wrapped white shemagh.',
    backgroundDescription: 'a solid, cool-toned slate blue or dark grey background with clean, professional lighting.',
  },
} as const;

export type StyleKey = keyof typeof STYLES;


// --- INTERNATIONALIZATION (i18n) ---

const translations = {
  en: {
    appName: 'Egal',
    mainHeading: 'Saudi Digital Identity in Seconds.',
    uploadButton: 'Upload Photo',
    uploadSubText: 'or drag and drop a PNG, JPG, or WEBP file (max 5MB)',
    dropPrompt: 'Drop image to upload',
    toggleLanguage: 'Switch to Arabic',
    selectStyles: 'Choose Your Style',
    selectStylesSub: 'Select one or more styles for your new headshot.',
    yourPortrait: 'Your Portrait',
    changePhotoButton: 'Change Photo',
    selectAll: 'Select All (6)',
    deselectAll: 'Deselect All',
    generateButton: 'Generate',
    generatingTitle: 'Crafting Your Identity...',
    generatingSub: 'This may take a moment. Please wait.',
    generationFailed: 'Generation Failed',
    tryAgainButton: 'Try Again',
    regenerateAllButton: 'Regenerate All',
    startOverButton: 'Start Over',
    downloadButton: 'Download',
    regenerateButton: 'Regenerate',
    discardButton: 'Discard',
    resultsTitle: 'Your Headshots Are Ready',
    resultsSub: 'Download your favorites or regenerate to get a new look.',
    footerCopyright: '© 2025 Egal. All Rights Reserved.',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    errorInvalidFileType: 'Invalid file type. Please upload a PNG, JPG, or WEBP.',
    errorFileTooLarge: 'File is too large. Please upload an image under 5MB.',
    errorUnknown: 'An unknown error occurred.',
    // Style Names
    style_executive_name: 'Executive Thobe',
    style_executive_desc: 'A pristine, sharp look for the modern professional.',
    style_bisht_name: 'Formal Bisht',
    style_bisht_desc: 'The peak of elegance for formal and official occasions.',
    style_shemagh_name: 'Modern Shemagh',
    style_shemagh_desc: 'A confident and contemporary take on a classic style.',
    style_ghutra_name: 'Classic Ghutra',
    style_ghutra_desc: 'Timeless, formal, and impeccably balanced heritage.',
    style_luxury_name: 'Subtle Luxury',
    style_luxury_desc: 'Refined taste shown through premium fabric and detail.',
    style_visionary_name: 'Visionary Leader',
    style_visionary_desc: 'A bold, forward-thinking look with a modern color palette.',
    // Modal Content
    privacyTitle: 'Privacy Policy',
    privacyContent: `Effective Date: October 2025

1. Our Commitment to Your Privacy
Egal ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains our principles regarding your data when you use the Egal web application (the "Service"). Our core principle is simple: we do not store, keep, or share your photos.

2. No Data Retention
Your privacy is paramount. We do not store, save, log, or retain any of the images you upload or the headshots generated by the Service. All processing is performed ephemerally (in-memory) and all data related to your images is permanently discarded immediately after your session ends or the generation is complete.

3. Information We Do Not Collect
We do not collect any Personally Identifiable Information (PII). Since you do not create an account, we have no access to your name, email address, or any other personal data. We do not use cookies or tracking technologies.

4. How Your Image is Used
Your uploaded image is used for the sole purpose of generating your professional headshot during your active session. It is sent to our AI model for processing and is not used for any other purpose, such as model training or analytics.

5. Data Security
We implement technical measures to protect your data during the brief processing period. All data is handled over secure, encrypted connections (HTTPS).

6. Children’s Privacy
Our Service is not intended for use by anyone under the age of 13. We do not knowingly collect any information from children.

7. Changes to This Privacy Policy
We may update this Privacy Policy from time to time. Any changes will be posted on this page. We encourage you to review this Privacy Policy periodically.

8. Contact Us
If you have any questions about this Privacy Policy, please contact us at: yaljohani@ai-egal.com`,
    termsTitle: 'Terms of Service',
    termsContent: `Effective Date: October 2025

Welcome to Egal. These Terms of Service ("Terms") govern your use of the Egal web application (the "Service"). By using our Service, you agree to these Terms.

1. The Service
Egal provides an AI-powered tool to transform your uploaded portrait into a professional headshot in authentic Saudi attire ("Generated Images").

2. User Responsibilities
You are solely responsible for the image you upload ("User Content"). You represent and warrant that you own or have the necessary rights and permissions to use your User Content with our Service. You agree not to upload any content that is illegal, defamatory, obscene, or infringing on the rights of others.

3. Intellectual Property Rights
You retain all ownership rights to your User Content. We retain all rights to the Service itself. Subject to your compliance with these Terms, you own the Generated Images you create and may use them for any personal or commercial purpose.

4. Acceptable Use
You agree not to use the Service to:
- Create harmful, deceptive, or offensive content.
- Infringe on any third party's intellectual property or privacy rights.
- Attempt to reverse-engineer, decompile, or otherwise discover the source code of the Service.

5. Disclaimer of Warranties
The Service is provided on an "AS IS" and "AS AVAILABLE" basis without any warranties of any kind, express or implied. We do not warrant that the Service will be error-free, uninterrupted, or that the Generated Images will meet your specific requirements.

6. Limitation of Liability
To the fullest extent permitted by law, Egal shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the Service.

7. Governing Law
These Terms shall be governed by the laws of the Kingdom of Saudi Arabia, without regard to its conflict of law provisions.

8. Changes to These Terms
We reserve the right to modify these Terms at any time. We will post the revised Terms on this page. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms.

9. Contact Us
If you have any questions about these Terms, please contact us at: yaljohani@ai-egal.com`,
  },
  ar: {
    appName: 'عِقال',
    mainHeading: 'هويتك الرقمية السعودية في ثوانٍ',
    uploadButton: 'ارفع الصورة',
    uploadSubText: 'أو قم بسحب وإفلات ملف PNG أو JPG أو WEBP (بحد أقصى 5 ميجابايت)',
    dropPrompt: 'أفلت الصورة للرفع',
    toggleLanguage: 'Switch to English',
    selectStyles: 'اختر إطلالتك',
    selectStylesSub: 'اختر إطلالة واحدة أو أكثر لصورتك الاحترافية الجديدة',
    yourPortrait: 'صورتك',
    changePhotoButton: 'تغيير الصورة',
    selectAll: 'تحديد الكل (٦)',
    deselectAll: 'إلغاء تحديد الكل',
    generateButton: 'إنشاء',
    generatingTitle: 'جاري تصميم هويتك...',
    generatingSub: 'قد يستغرق هذا بعض الوقت. يرجى الانتظار',
    generationFailed: 'فشل الإنشاء',
    tryAgainButton: 'إعادة المحاولة',
    regenerateAllButton: 'إعادة إنشاء الكل',
    startOverButton: 'البدء من جديد',
    downloadButton: 'تحميل',
    regenerateButton: 'إعادة إنشاء',
    discardButton: 'تجاهل',
    resultsTitle: 'صورك الاحترافية جاهزة',
    resultsSub: 'حمّل صورك المفضلة أو أعد إنشائها للحصول على إطلالة جديدة.',
    footerCopyright: '© ٢٠٢٥ عِقال. جميع الحقوق محفوظة.',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الخدمة',
    errorInvalidFileType: 'نوع الملف غير صالح. يرجى تحميل ملف PNG، JPG، أو WEBP.',
    errorFileTooLarge: 'حجم الملف كبير جدًا. يرجى تحميل صورة أقل من 5 ميجابايت.',
    errorUnknown: 'حدث خطأ غير معروف.',
    // Style Names
    style_executive_name: 'ثوب رسمي',
    style_executive_desc: 'إطلالة نقية وحادة للمحترفين العصريين.',
    style_bisht_name: 'بشت رسمي',
    style_bisht_desc: 'قمة الأناقة للمناسبات الرسمية والرسميات.',
    style_shemagh_name: 'شماغ عصري',
    style_shemagh_desc: 'تجسيد واثق ومعاصر لأسلوب كلاسيكي.',
    style_ghutra_name: 'غترة كلاسيكية',
    style_ghutra_desc: 'تراث أصيل، رسمي، ومتوازن بإتقان.',
    style_luxury_name: 'فخامة هادئة',
    style_luxury_desc: 'ذوق رفيع يتجلى في فخامة القماش ودقة التفاصيل.',
    style_visionary_name: 'قائد ملهم',
    style_visionary_desc: 'إطلالة جريئة وذات رؤية مستقبلية بألوان عصرية.',
    // Modal Content
    privacyTitle: 'سياسة الخصوصية',
    privacyContent: `تاريخ السريان: أكتوبر ٢٠٢٥

١. التزامنا بخصوصيتك
يلتزم "عِقال" ("نحن"، "لنا"، أو "خاصتنا") بحماية خصوصيتك. توضح سياسة الخصوصية هذه مبادئنا المتعلقة ببياناتك عند استخدامك لتطبيق الويب "عِقال" ("الخدمة"). مبدأنا الأساسي بسيط: نحن لا نخزن أو نحتفظ أو نشارك صورك.

٢. عدم الاحتفاظ بالبيانات
خصوصيتك لها أهمية قصوى. نحن لا نخزن أو نحفظ أو نسجل أو نحتفظ بأي من الصور التي ترفعها أو الصور الاحترافية التي تنشئها الخدمة. تتم جميع عمليات المعالجة بشكل مؤقت (في الذاكرة) ويتم التخلص من جميع البيانات المتعلقة بصورك بشكل دائم فور انتهاء جلستك أو اكتمال الإنشاء.

٣. المعلومات التي لا نجمعها
نحن لا نجمع أي معلومات تعريف شخصية (PII). بما أنك لا تنشئ حسابًا، فليس لدينا أي وصول إلى اسمك أو عنوان بريدك الإلكتروني أو أي بيانات شخصية أخرى. نحن لا نستخدم ملفات تعريف الارتباط أو تقنيات التتبع.

٤. كيف يتم استخدام صورتك
تُستخدم صورتك المرفوعة لغرض وحيد وهو إنشاء صورتك الاحترافية خلال جلستك النشطة. يتم إرسالها إلى نموذج الذكاء الاصطناعي الخاص بنا للمعالجة ولا تُستخدم لأي غرض آخر، مثل تدريب النماذج أو التحليلات.

٥. أمن البيانات
نحن نطبق إجراءات فنية لحماية بياناتك خلال فترة المعالجة القصيرة. يتم التعامل مع جميع البيانات عبر اتصالات آمنة ومُشفرة (HTTPS).

٦. خصوصية الأطفال
خدمتنا غير مخصصة للاستخدام من قبل أي شخص دون سن ١٣ عامًا. نحن لا نجمع عن قصد أي معلومات من الأطفال.

٧. التغييرات على سياسة الخصوصية هذه
قد نقوم بتحديث سياسة الخصوصية هذه من وقت لآخر. سيتم نشر أي تغييرات على هذه الصفحة. نشجعك على مراجعة سياسة الخصوصية هذه بشكل دوري.

٨. اتصل بنا
إذا كان لديك أي أسئلة حول سياسة الخصوصية هذه، يرجى الاتصال بنا على: yaljohani@ai-egal.com`,
    termsTitle: 'شروط الخدمة',
    termsContent: `تاريخ السريان: أكتوبر ٢٠٢٥

أهلاً بك في "عِقال". تحكم شروط الخدمة هذه ("الشروط") استخدامك لتطبيق الويب "عِقال" ("الخدمة"). باستخدامك لخدمتنا، فإنك توافق على هذه الشروط.

١. الخدمة
يوفر "عِقال" أداة مدعومة بالذكاء الاصطناعي لتحويل صورتك المرفوعة إلى صورة احترافية بالزي السعودي الأصيل ("الصور المُنشأة").

٢. مسؤوليات المستخدم
أنت وحدك المسؤول عن الصورة التي ترفعها ("محتوى المستخدم"). أنت تقر وتضمن أنك تملك أو لديك الحقوق والأذونات اللازمة لاستخدام محتوى المستخدم الخاص بك مع خدمتنا. أنت توافق على عدم رفع أي محتوى غير قانوني أو تشهيري أو فاحش أو ينتهك حقوق الآخرين.

٣. حقوق الملكية الفكرية
أنت تحتفظ بجميع حقوق الملكية لمحتوى المستخدم الخاص بك. نحن نحتفظ بجميع الحقوق في الخدمة نفسها. مع مراعاة امتثالك لهذه الشروط، فإنك تملك الصور المُنشأة التي تنشئها ويجوز لك استخدامها لأي غرض شخصي أو تجاري.

٤. الاستخدام المقبول
أنت توافق على عدم استخدام الخدمة في:
- إنشاء محتوى ضار أو خادع أو مسيء.
- انتهاك حقوق الملكية الفكرية أو حقوق الخصوصية لأي طرف ثالث.
- محاولة إجراء هندسة عكسية أو فك تجميع أو اكتشاف الكود المصدري للخدمة.

٥. إخلاء المسؤولية عن الضمانات
يتم توفير الخدمة "كما هي" و "حسب توفرها" دون أي ضمانات من أي نوع، سواء كانت صريحة أو ضمنية. نحن لا نضمن أن الخدمة ستكون خالية من الأخطاء أو دون انقطاع، أو أن الصور المُنشأة ستلبي متطلباتك المحددة.

٦. تحديد المسؤولية
إلى أقصى حد يسمح به القانون، لن يكون "عِقال" مسؤولاً عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية أو عقابية ناتجة عن استخدامك للخدمة.

٧. القانون الحاكم
تخضع هذه الشروط لقوانين المملكة العربية السعودية، بغض النظر عن تعارضها مع أحكام القانون.

٨. التغييرات على هذه الشروط
نحتفظ بالحق في تعديل هذه الشروط في أي وقت. سنقوم بنشر الشروط المعدلة على هذه الصفحة. استمرارك في استخدام الخدمة بعد أي من هذه التغييرات يشكل قبولك للشروط الجديدة.

٩. اتصل بنا
إذا كان لديك أي أسئلة حول هذه الشروط، يرجى الاتصال بنا على: yaljohani@ai-egal.com`,
  },
};

export function t(lang: 'en' | 'ar', key: keyof typeof translations.en): string {
    return translations[lang][key] || translations.en[key];
}